import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { BadgeCheck, Bookmark, CheckCircle2, CreditCard, MapPin, Share2, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { PageShell } from "@/components/offerme";
import { explainOffer } from "@/lib/ai.functions";
import coffee from "@/assets/merchants/caribou.jpg";

export const Route = createFileRoute("/offer/caribou-coffee")({
  head: () => ({ meta: [
    { title: "Caribou Coffee Demo Offer — OfferMe" }, { name: "description", content: "Preview a demo Caribou Coffee card offer and estimated savings calculator." },
    { property: "og:title", content: "Caribou Coffee Demo Offer — OfferMe" }, { property: "og:description", content: "Preview a demo card offer and savings calculator." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: OfferDetailPage,
});

function OfferDetailPage() {
  const [amount, setAmount] = useState(5);
  const saving = amount * .2;
  return <PageShell><section className="mx-auto max-w-[1420px] px-4 py-8"><p className="mb-5 text-xs text-muted-foreground">Home / Coffee & Roasters / <b className="text-foreground">Caribou Coffee Demo Offer</b></p><div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-start"><div className="space-y-5"><article className="overflow-hidden rounded-xl bg-card soft-shadow"><div className="relative aspect-[1.75/1] overflow-hidden"><img src={coffee} alt="Caribou Coffee storefront" width={1200} height={760} className="h-full w-full object-cover" /><span className="absolute left-4 top-4 rounded-full bg-rose-soft px-4 py-2 text-xs font-bold text-rose">BEST DEMO OFFER FOR YOU</span><span className="absolute bottom-5 left-5 rounded-xl bg-rose px-4 py-2 text-3xl font-extrabold text-rose-foreground">20% OFF</span></div><div className="p-6"><p className="text-[10px] font-bold uppercase text-rose">Specialty coffee & bakery · Demo merchant</p><h1 className="mt-2 text-3xl font-extrabold">Handcrafted Espresso, Cold Brews & Fresh Bakery</h1><div className="mt-5 flex items-center justify-between rounded-xl bg-rose-soft/60 p-4"><div><small className="font-bold text-rose">PRIMARY ELIGIBLE CARD</small><b className="mt-1 block">NBK Visa Platinum</b></div><span className="rounded-full bg-card px-3 py-2 text-[10px] font-bold">Instant Tap Perk</span></div><p className="mt-5 text-sm leading-6 text-muted-foreground">Demonstration terms only. Confirm all eligibility, dates, branches, and redemption instructions directly with the issuing bank before purchase.</p><div className="mt-5 flex flex-wrap gap-5 text-xs font-semibold"><span><MapPin className="mr-1 inline h-4 w-4 text-rose" />Kuwait branches</span><span><CreditCard className="mr-1 inline h-4 w-4 text-rose" />POS demo</span><span><CheckCircle2 className="mr-1 inline h-4 w-4 text-rose" />No minimum shown</span></div></div></article>
        <section className="rounded-xl bg-secondary p-5"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold">Other Eligible Cards In Your Wallet</h2><small>Tap to switch simulator</small></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-card p-5"><b>Boubyan Bank Visa</b><p className="mt-3 text-2xl font-extrabold text-rose">15% <small className="text-xs font-normal text-foreground">demo refund</small></p></div><div className="rounded-xl bg-card p-5"><b>Gulf Bank red™</b><p className="mt-3 text-2xl font-extrabold text-rose">BOGO <small className="text-xs font-normal text-foreground">demo pastry</small></p></div></div></section>
        <section className="rounded-xl bg-card p-6 soft-shadow"><h2 className="font-bold">ⓘ Terms & Redemption Checklist</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-muted-foreground"><li>Available only to eligible cardholders, subject to issuer confirmation.</li><li>Demo discount applies to standard menu pricing.</li><li>Cannot be assumed combinable with other promotions.</li><li>Confirm participating locations before purchase.</li></ul></section></div>
      <aside className="sticky top-24 rounded-xl bg-card p-6 offer-shadow"><div className="flex justify-between"><div><h2 className="text-2xl font-extrabold">Savings Calculator</h2><p className="text-xs text-muted-foreground">See a demo estimate before you order</p></div><span className="h-fit rounded-full bg-rose-soft px-3 py-1 text-[9px] font-bold text-rose">DEMO RATE</span></div><label className="mt-6 block text-xs font-bold">Estimated Order Total</label><div className="mt-2 flex items-center rounded-xl bg-secondary px-4"><input type="number" min="1" max="50" step=".5" value={amount} onChange={(event) => setAmount(Number(event.target.value))} className="h-14 min-w-0 flex-1 bg-transparent text-2xl font-bold outline-none" /><b className="text-rose">KD</b></div><div className="mt-3 grid grid-cols-5 gap-2">{[2.5,5,10,15,25].map((value) => <Button key={value} variant={amount === value ? "default" : "secondary"} size="sm" className="px-1 text-[10px]" onClick={() => setAmount(value)}>{value.toFixed(3)}</Button>)}</div><input aria-label="Order total" type="range" min="1" max="50" step=".5" value={amount} onChange={(event) => setAmount(Number(event.target.value))} className="mt-5 w-full accent-current" /><div className="mt-6 rounded-xl bg-secondary p-5"><div className="flex justify-between text-sm"><span>Original Menu Price</span><b>{amount.toFixed(3)} KD</b></div><div className="mt-3 flex justify-between border-b border-border pb-4 text-sm text-rose"><span>NBK 20% Instant Savings</span><b>−{saving.toFixed(3)} KD</b></div><div className="mt-4 flex items-end justify-between"><small className="font-bold">YOU PAY AT POS</small><b className="text-4xl">{(amount-saving).toFixed(3)} <small className="text-base text-rose">KD</small></b></div></div><Button className="mt-5 h-12 w-full rounded-full"><BadgeCheck /> Show Demo Offer Code</Button><div className="mt-3 grid grid-cols-2 gap-2"><Button variant="secondary" className="rounded-full"><Bookmark /> Save</Button><Button variant="secondary" className="rounded-full"><Share2 /> Share</Button></div><p className="mt-5 text-center text-[10px] text-muted-foreground">Demo calculation only · Confirm with the issuing bank</p></aside></div></section></PageShell>;
}