/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MyCardsRouteImport } from './routes/my-cards'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as OfferCaribouCoffeeRouteImport } from './routes/offer.caribou-coffee'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCardsRoute = MyCardsRouteImport.update({
  id: '/my-cards',
  path: '/my-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferCaribouCoffeeRoute = OfferCaribouCoffeeRouteImport.update({
  id: '/offer/caribou-coffee',
  path: '/offer/caribou-coffee',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-cards': typeof MyCardsRoute
  '/offers': typeof OffersRoute
  '/savings': typeof SavingsRoute
  '/offer/caribou-coffee': typeof OfferCaribouCoffeeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-cards': typeof MyCardsRoute
  '/offers': typeof OffersRoute
  '/savings': typeof SavingsRoute
  '/offer/caribou-coffee': typeof OfferCaribouCoffeeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-cards': typeof MyCardsRoute
  '/offers': typeof OffersRoute
  '/savings': typeof SavingsRoute
  '/offer/caribou-coffee': typeof OfferCaribouCoffeeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/my-cards'
    | '/offers'
    | '/savings'
    | '/offer/caribou-coffee'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/my-cards'
    | '/offers'
    | '/savings'
    | '/offer/caribou-coffee'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/my-cards'
    | '/offers'
    | '/savings'
    | '/offer/caribou-coffee'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MyCardsRoute: typeof MyCardsRoute
  OffersRoute: typeof OffersRoute
  SavingsRoute: typeof SavingsRoute
  OfferCaribouCoffeeRoute: typeof OfferCaribouCoffeeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-cards': {
      id: '/my-cards'
      path: '/my-cards'
      fullPath: '/my-cards'
      preLoaderRoute: typeof MyCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/caribou-coffee': {
      id: '/offer/caribou-coffee'
      path: '/offer/caribou-coffee'
      fullPath: '/offer/caribou-coffee'
      preLoaderRoute: typeof OfferCaribouCoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MyCardsRoute: MyCardsRoute,
  OffersRoute: OffersRoute,
  SavingsRoute: SavingsRoute,
  OfferCaribouCoffeeRoute: OfferCaribouCoffeeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
